# Generated by Django 3.2.18 on 2025-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(
                max_length=10,
                choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado')],
                default='Disponible'
            ),
        ),
    ]

